default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost

development:
  <<: *default
  database: bitly-clone_dev

test:
  <<: *default
  database: bitly-clone_test
  host: localhost
  username: postgres
